<?php
declare(strict_types=1);

namespace Sirius\Orm\Tests\Action;

use Sirius\Orm\Action\BaseAction;

class FakeThrowsException extends BaseAction
{
    public function __construct() {}

    protected function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }
}